a=int(input("Value of a: "))
b=int(input("Value of b: "))
c=int(input("Value of c: "))
print()
root1=(-1*b + (b*b-4*a*c)**0.5)/(2*a)
root2=(-1*b - (b*b-4*a*c)**0.5)/(2*a)
print(f"The roots are {root1} and {root2}")